### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by yiranli624** [mr-ryan12/intention-timer#28]
Over all really nice work! I see clean and dry code with clear logic.  Great structure with good naming conventions.
I would just add that in general, yall could think about single responsibility more. What is class responsible for? Does it need to access or mutate something involving UI? If a function is solely involving class properties, should it live in method or should it be a function?

For example, the timer feature. Currently the event listener in main is linked to a function that invokes a method in Activity, then that method calls function decrement in main, which involves data from Activity. 
Confusing, right? It is unclear what responsibility that should belong to Activity, and what should belong to main. 
In another word, when thinking about this feature, one could expect the event listener ties to a function that includes two parts. One is calling and gather data from Activity, the other is updating UI base on the mentioned data.
Same rule goes to the method `saveToStorage` in Activity, it includes calling functions that's not necessary.

nit: 
a) In general, I would recommend to use object when you have more than two params. It gives you a cleaner look and more flexibility.
b) One line functions such as `displayComplete` `timerAtZero` that only being used once, doesn't seem necessary to make it into a function.
c) `hide` and `show` can be refactored into one function that can be used for multiple elements. Then function such as `hideTimer` can be much cleaner.
d) Look into ternary, it could replace `if condition` when fit.

**Comment by yiranli624** [comment]
From UI side:
a) There's no errors display if min and sec input fields are missing.  Also once errors are out, it doesn't get removed even when value is refilled. It can cause confusion in some cases. 
For example, first I forgot to select type and goal, hit start, i see errors. Then I select a type and goal, but didn't select a timer, I see the same error, but that's not right since I did select a type and goal. How should i proceed as a user?

b) Once I start the timer, I'm still able to click the start button, that accelerated the count down. It would be safer to disable the button during the count down, so there's less chances user can cause unexpected bugs.

**Comment by Alynn022** [comment]
Thank you so much for your feedback! We appreciate your time so much! We disabled the button, and now our timer isn't decrementing faster when clicked.
